#include "interrupts.h"

char *int_names[] = {
    "Reset",
    "Reserved1",
    "Reserved2",
    "Reserved3",
    "Reserved4",
    "Reserved5",
    "Reserved6",
    "NMI",
    "TRAPA 0",
    "TRAPA 1",
    "TRAPA 2",
    "TRAPA 3",
    "Reserved12",
    "Sleep",
    "Reserved14",
    "Reserved15",
    "IRQ0",
    "IRQ1",
    "IRQAEC",
    "Reserved19",
    "Reserved20",
    "COMP0",
    "COMP1",
    "0.25s RTC",
    "0.5s RTC",
    "1s RTC",
    "1m RTC",
    "1h RTC",
    "1d RTC",
    "1w RTC",
    "Free RTC",
    "WDT",
    "Async evt counter",
    "Timer B1",
    "SSU/IIC2",
    "Timer W",
    "Reserved36",
    "SCI3",
    "A/D",
    "Reserved39"
};